# Site settings
title: Clout Atlas
email: open-disclosure-sf@groups.google.com
description: > # this means to ignore newlines until "baseurl:"
  Government transparency, in the form of continuous and timely disclosure of
  city officials’ activities, inside and outside government as it relates to
  their public duties is the mechanism that facilitates trust.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cloutatlas.org" # the base hostname & protocol for your site
twitter_username: sfbrigade
github_username:  sfbrigade

# Build settings
markdown: kramdown
